#AndroidIDE: enforce UTF-8 & locale for Gradle daemon
#Thu Mar 26 12:13:30 GMT 2026
android.enableAppCompileTimeRClass=false
android.uniquePackageNames=false
android.nonTransitiveRClass=true
android.usesSdkInManifest.disallowed=false
android.dependency.useConstraints=true
android.builtInKotlin=false
systemProp.user.language=en
systemProp.user.country=US
systemProp.java.net.preferIPv4Stack=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding\=UTF-8
android.useAndroidX=true
android.r8.optimizedResourceShrinking=false
systemProp.https.protocols=TLSv1.2,TLSv1.3
kotlin.code.style=official
android.defaults.buildfeatures.resvalues=true
systemProp.org.gradle.internal.http.connectionTimeout=120000
systemProp.org.gradle.internal.http.socketTimeout=120000
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.r8.strictFullModeForKeepRules=false
systemProp.sun.jnu.encoding=UTF-8
android.newDsl=false
systemProp.file.encoding=UTF-8
